"""initial schema

Revision ID: ec454021f6b8
Revises: 
Create Date: 2026-09-27 15:55:03.493265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec454021f6b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='risklevel', native_enum=False, length=16), nullable=False),
    sa.Column('args_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('render_template', sa.Text(), nullable=False),
    sa.Column('blast_radius', sa.Text(), nullable=True),
    sa.Column('if_denied', sa.Text(), nullable=True),
    sa.Column('default_timeout', postgresql.INTERVAL(), server_default=sa.text("interval '4 hours'"), nullable=False),
    sa.Column('on_timeout', sa.Enum('approve', 'deny', 'escalate', name='ontimeout', native_enum=False, length=16), server_default='deny', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("on_timeout IN ('approve', 'deny', 'escalate')", name=op.f('ck_actions_on_timeout_valid')),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_actions_risk_level_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions')),
    sa.UniqueConstraint('name', name=op.f('uq_actions_name'))
    )
    op.create_table('principals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_principals')),
    sa.UniqueConstraint('email', name=op.f('uq_principals_email'))
    )
    op.create_table('requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('agent_run_id', sa.String(length=200), nullable=False),
    sa.Column('agent_name', sa.String(length=200), nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('rendered', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', 'ESCALATED', 'EXPIRED', 'CONSUMED', name='requeststatus', native_enum=False, length=16), server_default='PENDING', nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'DENIED', 'ESCALATED', 'EXPIRED', 'CONSUMED')", name=op.f('ck_requests_status_valid')),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('fk_requests_action_id_actions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_requests_idempotency_key'))
    )
    op.create_index('ix_requests_status_expires_at', 'requests', ['status', 'expires_at'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.Enum('approve', 'deny', 'modify', name='verdict', native_enum=False, length=16), nullable=False),
    sa.Column('modified_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rendered_snapshot', sa.Text(), nullable=False),
    sa.CheckConstraint("(verdict = 'modify') = (modified_args IS NOT NULL)", name=op.f('ck_decisions_notify_has_args')),
    sa.CheckConstraint("verdict <> 'deny' OR length(trim(coalesce(comment, ''))) > 0", name=op.f('ck_decisions_deny_has_reason')),
    sa.CheckConstraint("verdict IN ('approve', 'deny', 'modify')", name=op.f('ck_decisions_verdict_valid')),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], name=op.f('fk_decisions_principal_id_principals')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_decisions_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions')),
    sa.UniqueConstraint('request_id', name=op.f('uq_decisions_request_id'))
    )
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='outboxstatus', native_enum=False, length=16), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'sent', 'failed')", name=op.f('ck_outbox_status_valid')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_outbox_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox'))
    )
    op.create_index('ix_outbox_date', 'outbox', ['next_attempt_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('request_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_request_events_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_events'))
    )
    op.create_index('ix_request_events_request_id_at', 'request_events', ['request_id', 'at'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('step_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('principal_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('escalate_after', postgresql.INTERVAL(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cardinality(principal_ids) > 0 OR role IS NOT NULL', name=op.f('ck_routes_has_target')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_routes_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes')),
    sa.UniqueConstraint('request_id', 'step_index', name=op.f('uq_routes_request_id_step_index'))
    )
    op.execute("""
        CREATE OR REPLACE FUNCTION izin_forbid_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'izin: % on % is forbidden (append-only)', TG_OP, TG_TABLE_NAME
                USING ERRCODE = 'insufficient_privilege';
        END $$;
    """)

    for table in ("decisions", "request_events", "routes"):
        op.execute(f"""
            CREATE TRIGGER {table}_append_only
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION izin_forbid_mutation();
        """)
        # Row triggers don't fire on TRUNCATE; this closes that hole.
        op.execute(f"""
            CREATE TRIGGER {table}_no_truncate
            BEFORE TRUNCATE ON {table}
            FOR EACH STATEMENT EXECUTE FUNCTION izin_forbid_mutation();
        """)

    # §9.1: requests is "mutable, single column". Enforce exactly that.
    op.execute("""
        CREATE OR REPLACE FUNCTION izin_requests_guard() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'izin: requests are never deleted'
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            IF (to_jsonb(NEW) - 'status') IS DISTINCT FROM (to_jsonb(OLD) - 'status') THEN
                RAISE EXCEPTION 'izin: only requests.status may change'
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            RETURN NEW;
        END $$;
    """)
    op.execute("""
        CREATE TRIGGER requests_guard
        BEFORE UPDATE OR DELETE ON requests
        FOR EACH ROW EXECUTE FUNCTION izin_requests_guard();
    """)
    op.execute("""
        CREATE TRIGGER requests_no_truncate
        BEFORE TRUNCATE ON requests
        FOR EACH STATEMENT EXECUTE FUNCTION izin_forbid_mutation();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    op.drop_index('ix_request_events_request_id_at', table_name='request_events')
    op.drop_table('request_events')
    op.drop_index('ix_outbox_date', table_name='outbox', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('outbox')
    op.drop_table('decisions')
    op.drop_index('ix_requests_status_expires_at', table_name='requests')
    op.drop_table('requests')
    op.drop_table('principals')
    op.drop_table('actions')
    op.execute("DROP FUNCTION IF EXISTS izin_requests_guard()")
    op.execute("DROP FUNCTION IF EXISTS izin_forbid_mutation()")
    # ### end Alembic commands ###
